Atualização do sobre-nos
training-center/sobre pull request #26
Opened 2017-09-04 21:42 UTC by woliveiras

As imagens estão com link absoluto devido ao GitHub Pages se perder em nosso domínio.

Assim não quebra em trainingcenter.io. :)

Atenção aos erros de pt pra eu arrumar. :D

2017-09-04 21:54 UTC, gustavocardoso approved these changes

2017-09-04 22:01 UTC, diegomalone submitted a review, later dismissed

2017-09-04 23:24 UTC, adeonir commented on README.md
> -  <li><a href="https://www.reddit.com/r/trainingcentr/" target="_blank" title="Participe do nosso forum no Reddit">Participe do nosso forum no Reddit</a></li>
faltou acento em `fórum`

2017-09-04 23:25 UTC, adeonir commented on README.md
> +Uma comunidade **sem fins lucrativos** com a premissa de ajudar pessoas iniciantes ou não que tem dúvidas ou precisam de dicas para alavancar sua carreira na área de desenvolvimento de software ou só
Uma comunidade **sem fins lucrativos** com a premissa de ajudar pessoas, iniciantes ou não, que tem dúvidas, que precisam de dicas para alavancar sua carreira na área de desenvolvimento de software ou só querem fazer bons amigos e amigas para criarem um projeto juntos.

2017-09-04 23:26 UTC, adeonir commented on README.md
> +Conectamos pessoas que querem aprender algo relacionado a desenvolvimento de software com gente que pode lhes guiar.
... com gente que pode `guiá-las`.

2017-09-04 23:27 UTC, adeonir commented on README.md
> +Nós, como grupo que pode fazer algo pela sociedade, abraçamos a responsabilidade de ajudar as minorias buscando apoiar desde comunidades carentes, mulheres na tecnologia, comunidade LGBTI+ ou qualque
... outro grupo que `sofra` de alguma...

2017-09-04 23:27 UTC, adeonir commented on README.md
> +Estamos aqui da comunidade para a comunidade e buscando agregar valor a nossa sociedade.
Estamos aqui: da comunidade para a comunidade, buscando agregar valor à nossa sociedade.

2017-09-04 23:30 UTC, adeonir requested changes
Opa... marquei algumas correções necessárias.

2017-09-05 11:03 UTC, woliveiras commented on README.md
> -  <li><a href="https://www.reddit.com/r/trainingcentr/" target="_blank" title="Participe do nosso forum no Reddit">Participe do nosso forum no Reddit</a></li>
Essa linha foi removida, @adeonir :grimacing:

2017-09-05 11:05 UTC, woliveiras commented
Feito, @adeonir! :raised_hands:

2017-09-05 11:51 UTC, diegomalone requested changes
Marquei um pequeno detalhe que tinha sido solicitado pelo @adeonir

2017-09-05 11:51 UTC, diegomalone commented on README.md
> +Conectamos pessoas que querem aprender algo relacionado a desenvolvimento de software com gente que pode lhes guiá-las.
Aqui é pra remover o "lhes". [...] que pode guiá-las.

2017-09-05 12:44 UTC, gnbezerra commented on README.md
> +Uma comunidade **sem fins lucrativos** com a premissa de ajudar pessoas, iniciantes ou não, que tem dúvidas, que precisam de dicas para alavancar sua carreira na área de desenvolvimento de software o
Onde diz "que tem dúvidas" deveria ser "que têm dúvidas" (acento no 'e'), por causa do plural

2017-09-06 00:21 UTC, woliveiras commented on README.md
> +Conectamos pessoas que querem aprender algo relacionado a desenvolvimento de software com gente que pode lhes guiá-las.
EIIIITA! Olha a brecha! Valeu, @diegomalone

2017-09-06 00:21 UTC, woliveiras commented on README.md
> +Uma comunidade **sem fins lucrativos** com a premissa de ajudar pessoas, iniciantes ou não, que tem dúvidas, que precisam de dicas para alavancar sua carreira na área de desenvolvimento de software o
Valeu, @gnbezerra

2017-09-06 00:30 UTC, adeonir approved these changes

2017-09-06 00:51 UTC, diegomalone approved these changes

2017-09-06 16:50 UTC, merged