Create exemplo.md
training-center/sobre pull request #73
Opened 2018-04-25 23:04 UTC by woliveiras

## Queremos patrocínio do Bitbucket

A gente tá tentando fazer uma média pra reaver a possibilidade de um futuro patrocínio

- [x] tem um título legal
- [x] tem uma boa descrição
- [x] segue nosso COC

2018-04-25 23:07 UTC, khaosdoctor requested changes
Não gostei :(

2018-04-25 23:09 UTC, woliveiras commented
Oxi! Não gostou do que, tio?

2018-04-25 23:10 UTC, khaosdoctor requested changes

2018-04-25 23:10 UTC, khaosdoctor commented on exemplo.md
> +## Eu gosto do Bitbucket também
Mentira!

2018-04-25 23:10 UTC, woliveiras commented on exemplo.md
> +## Eu gosto do Bitbucket também
É verdade, mano!

2018-04-25 23:12 UTC, woliveiras commented
Não quero mais que meu PR seja parte desse projeto!

2018-04-25 23:12 UTC, closed without merging

2018-04-25 23:13 UTC, alinebastos commented
Que que eu perdi??? hahahahaha

2018-04-26 01:32 UTC, luizbills commented
Ainda é quarta-feira e vocês já estão enchendo a cara?

2018-04-26 02:44 UTC, khaosdoctor commented
Calma galera, era pro TC Talks 8 sobre PRs :D eu e o @woliveiras estamos em paz kk